### ISSUE TITLE
SConstruct TypeError: access: path should be string, bytes or os.PathLike, not NoneType

### ISSUE THREAD

**Issue by hemebond** [maiself/godot-python-extension#1]
Getting an error when trying to build on Debian Linux:

```
 $ scons godot=/home/james/.local/bin/godot4 
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
TypeError: access: path should be string, bytes or os.PathLike, not NoneType:
  File "/home/james/Workspace/godot-python-extension/SConstruct", line 139:
    opts.Update(env)
  File "/usr/lib/python3/dist-packages/SCons/Variables/__init__.py", line 230:
    option.validator(option.key, env.subst('${%s}'%option.key), env)
  File "/home/james/Workspace/godot-python-extension/tools/build_utils.py", line 167:
    if os.access(path, os.X_OK):

 $ python --version
Python 3.11.5

 $ scons --version
SCons by Steven Knight et al.:
	SCons: v4.4.0.fc8d0ec215ee6cba8bc158ad40c099be0b598297, Sat, 30 Jul 2022 14:11:34 -0700, by bdbaddog on M1Dog2021
	SCons path: ['/usr/lib/python3/dist-packages/SCons']
Copyright (c) 2001 - 2022 The SCons Foundation

```

**Comment by maiself** [comment]
Hi, thanks for the report!

There's definitely a bug there, however I'm not exactly sure whats going on. Based of the info given, my only guesses are that the path could be wrong, or the file isn't marked executable, but something else may be happening.

I've pushed an update to the related code which fixes the one error I spotted and adds a bit more descriptive error messages (02cf5b2). Could you please try again with the new code and report back?

**Comment by hemebond** [comment]
Thanks. I'm getting this error now:

```
$ scons godot=/home/james/.local/bin/godot4 
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.

scons: *** Path 'python_config' is not an executable found in PATH: 'python-config'
File "/home/james/Workspace/godot-python-extension/tools/build_utils.py", line 175, in validate_executable
```

**Comment by maiself** [comment]
I've pushed code to update the patch process during building and added version checks.

From the log I can see you're trying to build against Godot version 4.1.1. Unfortunately that version doesn't contain the required commits for this extension to work, Godot **4.2** or newer is needed. However even 4.2-dev5 doesn't contain the required commits. You will either have build Godot yourself, or download an **\*unstable\*** build from https://godotengine.github.io/godot-commit-artifacts/ (September 20th or later) until Godot 4.2 or 4.2-dev6 is released.

**Comment by hemebond** [comment]
Thank you. I wasn't able to get a 4.2 download so I'll try again after 4.2 is released.

**Comment by maiself** [comment]
Thanks for giving it a try and reporting the issues!

**Comment by hemebond** [comment]
Just an update to this. Compiled without issue with the latest 4.2.1 release. However I'm still trying to work out how to actually use/enable it. Neither the README here, nor other GDExtension documentation seems to mention it.
