### ISSUE TITLE
Macos build problems

### ISSUE THREAD

**Issue by fire** [maiself/godot-python-extension#11]
Tracking

**Comment by maiself** [comment]
Have you tried the extension on MacOS? This is the one platform I have no means of working with, so I have no idea what the state of things are.

**Comment by fire** [comment]
No github action builds exist for the mac

**Comment by Ivorforce** [comment]
The current state of things are easy to summarize: You cannot build on mac because there's no config for it.

```bash
❯ scons
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
Building for architecture universal on platform macos
KeyError: ('macos', 'universal'):
  File "/Users/lukas/dev/godot/godot-python-extension/SConstruct", line 289:
    prepared_python_config = prepare_python.platform_configs[(env['platform'], env['arch'])]
```

I work on a mac, so I should be able to whip up a config in `prepare_python.py` to support the platform. Might take a while though, depending on when I have time.
