### ISSUE TITLE
Can revise the github actions so they also check on push to master

### ISSUE THREAD

**Issue by fire** [maiself/godot-python-extension#14]
TL;DR 

Add push on master in the github actions.

Not able to make pr right now.

**Comment by maiself** [comment]
I think I'd be fine with this, and its a simple change correct?

This might be worth a separate issue, but I'm wondering if the action could package the artifacts of the various platform builds into a single archive ready to be used or uploaded as a release. I have a script locally that can download the artifacts and repackage, but a one button solution would be nice.

**Comment by Ivorforce** [comment]
This can be closed; it was addressed in cb651ca.

**Comment by fire** [comment]
Thanks
