### ISSUE TITLE
Package the artifacts of the various platform builds into a single archive

### ISSUE THREAD

**Issue by fire** [maiself/godot-python-extension#20]
Package the artifacts of the various platform builds into a single archive ready to be used or uploaded as a release.

Todo from https://github.com/maiself/godot-python-extension/issues/14

**Comment by fire** [comment]
Poked @Ughuuu

**Comment by Ughuuu** [comment]
Do same as we do in godot-sandbox: This is where we merge all packages into one: https://github.com/libriscv/godot-sandbox/blob/main/.github/workflows/runner.yml#L50
