### ISSUE TITLE
Document where to find releases better

### ISSUE THREAD

**Issue by Ivorforce** [maiself/godot-python-extension#23]
The current docs say one should look for builds in the releases section. The section is currently empty.

I have since figured out you can find releases in the GitHub actions. Unless (re-?) adopting the Releases as the official prebuilt binary download scheme is desired right now, the documentation should be changed to point to the GitHub action builds for now.

**Comment by maiself** [comment]
The github action builds arn't really release ready I think... It's been a while but I believe they might be missing some important files and need reorganizing before use.

However, I agree the documentation should probably point there, maybe with a note that the current situation is only temporary.

There's still one feature in the works (automatic type casting via type annotation) that I haven't been able to commit to the main branch yet, and that's what has held up doing a proper alpha release.
