### ISSUE TITLE
Unable to load GDExtension interface function string_new_with_utf8_chars_and_len2()

### ISSUE THREAD

**Issue by hemebond** [maiself/godot-python-extension#6]
Compiled the latest version and opened the project under `test/`. Unsure if there are specific steps required to enable or import it.

```
Godot Engine v4.2.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  Attempt to get non-existent interface function: string_new_with_utf8_chars_and_len2.
  src/extension/extension.cpp:348 - Unable to load GDExtension interface function string_new_with_utf8_chars_and_len2()
  core/extension/gdextension.cpp:748 - GDExtension initialization function 'python_extension_init' returned an error.
  Failed loading resource: res://python.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by maiself** [comment]
Ah, after the recent updates the extension requires Godot version 4.3. I can look into if it will be possible to continue supporting 4.2, but the addition of the `PackedVector4Array` variant type may complicate that.

**Comment by maiself** [comment]
Turns out it wasn't too difficult to make things work across versions, commits 9cf94f1 and 031908e enable this. So for now its possible to continue using the extension with Godot 4.2, tho I can't guarantee that that will be possible forever.
